[package]

name = "timely"
version = "0.0.10"
authors = ["Frank McSherry <fmcsherry@me.com>"]

description = "A low-latency data-parallel dataflow system in Rust"

# These URLs point to more information about the repository
documentation = "https://frankmcsherry.github.com/timely-dataflow"
homepage = "https://github.com/frankmcsherry/timely-dataflow"
repository = "https://github.com/frankmcsherry/timely-dataflow.git"
keywords = ["timely", "dataflow"]
license = "MIT"

# [dependencies.timely_communication]
# path="./communication"

[features]
default=[]
logging=[]

[dependencies]
abomonation="*"
timely_communication="*"
byteorder="*"
time="*"

[dev-dependencies]
getopts="*"
rand="*"

[dev-dependencies.radix_sort]
git="https://github.com/frankmcsherry/radix-sort"
