[package]
name = "timely_communication"
version = "0.5.1"
authors = ["Frank McSherry <fmcsherry@me.com>"]

description = "Communication layer for timely dataflow"

# These URLs point to more information about the repository
documentation = "https://frankmcsherry.github.com/timely-dataflow"
homepage = "https://github.com/frankmcsherry/timely-dataflow"
repository = "https://github.com/frankmcsherry/timely-dataflow.git"
keywords = ["timely", "dataflow"]
license = "MIT"

[features]
default=["arg_parse"] # ["logging"]
arg_parse=["getopts"]

[dependencies]
byteorder="1"
getopts={version="0.2.14", optional=true}
time="0.1.34"
abomonation = { git = "https://github.com/frankmcsherry/abomonation" }
abomonation_derive = "0.3"
bytes = { path = "../bytes" }

[[examples]]
features = "arg_parse"

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
